FROM ubuntu:xenial

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install mysql-server-5.7

ARG MYSQL_USER=kimo
ARG MYSQL_PASSWORD=123

ADD docker-init-mysql.sh /tmp/

RUN ["bash", "/tmp/docker-init-mysql.sh"]

ENTRYPOINT ["mysqld"]

EXPOSE 3306